name: CI
on:
  push:
    branches: [develop] #branch in github

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npx prettier --c .
      - run: npm run ts-coverage
        env:
          CI: true
